import {
  ClerkProvider,
  SignedIn,
  SignedOut,
  SignIn,
} from "@clerk/nextjs";
import NavBar from "@/components/NavBar";
import "./globals.css";
import type { Metadata } from "next";
import localFont from "next/font/local";
import { Sign } from "crypto";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
        <body>
          <SignedIn>
          <NavBar/>
            {children}
          </SignedIn>

          {/* Content visible only when the user is signed out */}
          <SignedOut>
            <NavBar/>
            <SignIn/>
          </SignedOut>
        </body>
      </html>
    </ClerkProvider>
  );
}
